/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthorizationRouteImport } from './routes/authorization'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as FootprintScanIdRouteImport } from './routes/footprint.$scanId'
import { Route as ReportScanIdRouteImport } from './routes/report.$scanId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizationRoute = AuthorizationRouteImport.update({
  id: '/authorization',
  path: '/authorization',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const FootprintScanIdRoute = FootprintScanIdRouteImport.update({
  id: '/footprint/$scanId',
  path: '/footprint/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportScanIdRoute = ReportScanIdRouteImport.update({
  id: '/report/$scanId',
  path: '/report/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/authorization': typeof AuthorizationRoute
  '/monitor': typeof MonitorRoute
  '/trust': typeof TrustRoute
  '/footprint/$scanId': typeof FootprintScanIdRoute
  '/report/$scanId': typeof ReportScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/authorization': typeof AuthorizationRoute
  '/monitor': typeof MonitorRoute
  '/trust': typeof TrustRoute
  '/footprint/$scanId': typeof FootprintScanIdRoute
  '/report/$scanId': typeof ReportScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/authorization': typeof AuthorizationRoute
  '/monitor': typeof MonitorRoute
  '/trust': typeof TrustRoute
  '/footprint/$scanId': typeof FootprintScanIdRoute
  '/report/$scanId': typeof ReportScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/authorization'
    | '/monitor'
    | '/trust'
    | '/footprint/$scanId'
    | '/report/$scanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/authorization'
    | '/monitor'
    | '/trust'
    | '/footprint/$scanId'
    | '/report/$scanId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/authorization'
    | '/monitor'
    | '/trust'
    | '/footprint/$scanId'
    | '/report/$scanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthorizationRoute: typeof AuthorizationRoute
  MonitorRoute: typeof MonitorRoute
  TrustRoute: typeof TrustRoute
  FootprintScanIdRoute: typeof FootprintScanIdRoute
  ReportScanIdRoute: typeof ReportScanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorization': {
      id: '/authorization'
      path: '/authorization'
      fullPath: '/authorization'
      preLoaderRoute: typeof AuthorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footprint/$scanId': {
      id: '/footprint/$scanId'
      path: '/footprint/$scanId'
      fullPath: '/footprint/$scanId'
      preLoaderRoute: typeof FootprintScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$scanId': {
      id: '/report/$scanId'
      path: '/report/$scanId'
      fullPath: '/report/$scanId'
      preLoaderRoute: typeof ReportScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthorizationRoute: AuthorizationRoute,
  MonitorRoute: MonitorRoute,
  TrustRoute: TrustRoute,
  FootprintScanIdRoute: FootprintScanIdRoute,
  ReportScanIdRoute: ReportScanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
